SELECT TOP(1) P.ID,P.TITLE,P.LINK,P.TEXT,P.POST_DATE,P.TAGS, A.NAME, A.ID, S.NAME, S.ID FROM POSTS P WHERE P.ID = 2019289309482934
INNER JOIN AUTHORS A
ON P.AUTHOR_ID = A.ID 
INNER JOIN SECTIONS S
on P.SECTION_ID = S.ID; 




SELECT TOP(50) P.ID,P.TITLE,P.LINK,P.POST_DATE,P.TAGS A.NAME, A.ID FROM POSTS P WHERE P.SECTION_ID = 20292808302801
INNER JOIN AUTHORS A
ON P.AUTHOR_ID = A.ID
ORDER BY P.POST_DATE;


